export type Helpers =
  | 'camelCase'
  | 'constantCase'
  | 'dotCase'
  | 'kebabCase'
  | 'lowerCase'
  | 'pascalCase'
  | 'pathCase'
  | 'plural'
  | 'sentenceCase'
  | 'singular'
  | 'snakeCase'
  | 'titleCase'
  | 'unmodified'
